# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Levi Bostian
email: levi.bostian@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Personal site of Levi Bostian.
baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://levibostian.com" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
markdown: kramdown
sass:
  sass_dir: _sass

livereload: fales

mode: production

incremental: false

plugins:
  - jekyll-feed

exclude:
  - node_modules
  - vendor
  - Gemfile
  - Gemfile.lock

collections:
  freelance:
    output: true
    permalink: /archive/freelance/:path/
  internships:
    output: true
    permalink: /archive/internships/:path/
  mentoring:
    output: true
    permalink: /archive/mentoring/:path/
  opensource:
    output: true
    permalink: /archive/opensource/:path/
  products:
    output: true
    permalink: /archive/products/:path/
  publications:
    output: true
    permalink: /archive/publications/:path/
  services:
    output: true
    permalink: /archive/services/:path/
  talks:
    output: true
    permalink: /archive/talks/:path/
  tutorials:
    output: true
    permalink: /archive/tutorials/:path/
  writing:
    output: true
    permalink: /archive/writing/:path/
