baseURL: https://levi.earth/
defaultContentLanguage: en
title: Levi Bostian
enableGitInfo: true 
enableEmoji: true # Emoji list: https://gohugo.io/quick-reference/emojis/
theme: yue

params:
  _merge: deep # Import default config
  rssFullContent: true
  homePagerSize: 5
  sectionPagerSize: 10000 # Default: 10, set this to a large number to remove pagination
  images:
    # Default image used in Open Graph, see https://gohugo.io/templates/embedded/#configure-open-graph
    - static/img/favicon.ico

frontmatter:
  lastmod: ['lastmod', ':default'] # lastmod in front matter has highest precedence

languages:
  en:
    contentDir: content
    languageCode: en-US
    languageDirection: ltr
    languageName: English
    title: Levi Bostian # Shown in home page
    weight: 10
    menus:
      main:
        - name: Home   
          url: /
          weight: 1
        - name: GitHub
          url: https://github.com/levibostian/
          weight: 2
    params:
      dateFormat: Jan 02, 2006 # See https://gohugo.io/functions/time/format/
      author: Levi Bostian # Default author, supports single value or list, used in single page
      footer:
        copyright:
          author: Levi Bostian