name: Deploy and test site 

on: 
  push:
  pull_request:    
  release:
    types: [published]

jobs:
  test-deploy-site:
    name: Build, test, and deploy site
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.80.0'
          extended: true # required to compile SASS 
      - name: Build Hugo site
        run: hugo --minify 

      - name: Start local server to test 
        run: hugo server --disableLiveReload --port 1313 --baseURL http://localhost:1313/ &
      - name: Check for 404s
        uses: ruzickap/action-my-broken-link-checker@v2
        with:
          url: http://localhost:1313/
          cmd_params: "--skip-tls-verification"

      - name: Deploy to Netlify
        uses: nwtgck/actions-netlify@v1.2
        id: netlify-deploy
        with:
          publish-dir: './public'
          production-branch: main
          github-token: ${{ secrets.GITHUB_TOKEN }}
          deploy-message: "GitHub Action deploy to production"
          enable-commit-comment: false
          enable-pull-request-comment: true
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
        timeout-minutes: 1
      
