name: Deploy and test site 

on: 
  push:
  pull_request:    
  release:
    types: [published]

jobs:
  build-deploy-site:
    name: Build and deploy site
    runs-on: ubuntu-latest
    outputs:
      deploy-url: ${{ steps.netlify-deploy.outputs.deploy-url }}
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.80.0'
          extended: true # required to compile SASS 
      - name: Build Hugo site
        run: hugo --minify 
      - name: Deploy to Netlify
        uses: nwtgck/actions-netlify@v1.2
        id: netlify-deploy
        with:
          publish-dir: './public'
          production-branch: main
          github-token: ${{ secrets.GITHUB_TOKEN }}
          deploy-message: "GitHub Action deploy to production"
          enable-commit-comment: false
          enable-pull-request-comment: true
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
        timeout-minutes: 1
      
  test-404:
    name: Test 404s
    runs-on: ubuntu-latest
    needs: [build-deploy-site]
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - name: Test for 404s
        uses: ruzickap/action-my-broken-link-checker@v2
        with:
          url: ${{ needs.build-deploy-site.outputs.deploy-url }}

  test-performance:
    name: Test performance 
    runs-on: ubuntu-latest
    needs: [build-deploy-site]
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - name: Test via Lighthouse 
        uses: foo-software/lighthouse-check-action@v7.1.1
        with:
          urls: '${{ needs.build-deploy-site.outputs.deploy-url }}'
          gitHubAccessToken: ${{ secrets.READ_ONLY_BOT_TOKEN }}
          prCommentEnabled: true 
          prCommentSaveOld: false 
