name: Deploy site 

on:
  release:
    types: [published]

jobs:
  deploy-site:
    name: Deploy site
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.80.0'
          extended: true # required to compile SASS 
      - name: Build Hugo site
        run: hugo --minify 
      - name: Deploy to Netlify
        uses: nwtgck/actions-netlify@v1.2
        id: netlify-deploy
        with:
          publish-dir: './public'
          production-branch: main
          github-token: ${{ secrets.GITHUB_TOKEN }}
          deploy-message: "GitHub Action deploy to production"
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
        timeout-minutes: 1